/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next')['BButtonGroup']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardBody: typeof import('bootstrap-vue-next')['BCardBody']
    BCardFooter: typeof import('bootstrap-vue-next')['BCardFooter']
    BCardHeader: typeof import('bootstrap-vue-next')['BCardHeader']
    BCloseButton: typeof import('bootstrap-vue-next')['BCloseButton']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BDropdownMenu: typeof import('bootstrap-vue-next')['BDropdownMenu']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormFloatingLabel: typeof import('bootstrap-vue-next')['BFormFloatingLabel']
    BFormGrouop: typeof import('bootstrap-vue-next')['BFormGrouop']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BModalBody: typeof import('bootstrap-vue-next')['BModalBody']
    BModalHeader: typeof import('bootstrap-vue-next')['BModalHeader']
    BNav: typeof import('bootstrap-vue-next')['BNav']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BNavLink: typeof import('bootstrap-vue-next')['BNavLink']
    BOffcanvas: typeof import('bootstrap-vue-next')['BOffcanvas']
    BOffcanvasBody: typeof import('bootstrap-vue-next')['BOffcanvasBody']
    BOffcanvasHeader: typeof import('bootstrap-vue-next')['BOffcanvasHeader']
    BPagination: typeof import('bootstrap-vue-next')['BPagination']
    BTab: typeof import('bootstrap-vue-next')['BTab']
    BTabContent: typeof import('bootstrap-vue-next')['BTabContent']
    BTabPane: typeof import('bootstrap-vue-next')['BTabPane']
    BTabs: typeof import('bootstrap-vue-next')['BTabs']
  }
}
